import { getCMS } from './cms';

function parseHHMM(s){if(!s||typeof s!=='string')return null;const m=s.match(/^\s*(\d{1,2}):(\d{2})\s*$/);if(!m)return null;const h=parseInt(m[1],10),mm=parseInt(m[2],10);if(isNaN(h)||isNaN(mm))return null;return h*60+mm}
function hhmm(mins){if(mins==null)return'--:--';const h=Math.floor(mins/60),m=mins%60;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function statusForIntervals(intervals,now){if(!Array.isArray(intervals)||!intervals.length)return{openNow:false,until:'--:--',open:'--:--',close:'--:--'};const t=now.getHours()*60+now.getMinutes();for(const [a,b]of intervals){if(t>=a&&t<b)return{openNow:true,until:hhmm(b),open:hhmm(a),close:hhmm(b)}}const next=intervals.find(([a])=>t<a);if(next)return{openNow:false,until:hhmm(next[0]),open:hhmm(intervals[0][0]),close:hhmm(intervals[intervals.length-1][1])};return{openNow:false,until:'--:--',open:hhmm(intervals[0][0]),close:hhmm(intervals[intervals.length-1][1])}
}
function todayStatus(cms,now=new Date()){const key=['sun','mon','tue','wed','thu','fri','sat'][now.getDay()];const get=k=>{const v=cms?.[k];return typeof v==='string'&&v.trim()?v.trim():null};if(key==='fri'){const o1=parseHHMM(get('hours.fri.open1')),c1=parseHHMM(get('hours.fri.close1')),o2=parseHHMM(get('hours.fri.open2')),c2=parseHHMM(get('hours.fri.close2'));const iv=[];if(o1!=null&&c1!=null&&c1>o1)iv.push([o1,c1]);if(o2!=null&&c2!=null&&c2>o2)iv.push([o2,c2]);return statusForIntervals(iv,now)}else{const o=parseHHMM(get(`hours.${key}.open`)),c=parseHHMM(get(`hours.${key}.close`));const iv=[];if(o!=null&&c!=null&&c>o)iv.push([o,c]);return statusForIntervals(iv,now)}}
export async function getToday(){try{const cms=await getCMS();const s=todayStatus(cms||{});return{openNow:s.openNow,until:s.until,open:s.open,close:s.close,specials:[]}}catch{return{openNow:false,until:'--:--',open:'--:--',close:'--:--',specials:[]}}}
export async function getPayItForward(){return{available:7,contributed:124}}
export async function getFreeDrinkProgress(){return{current:3,target:10}}
